FROM python:3.12.4

#create directory
WORKDIR /app

#copy all the files
COPY . /app

#install dependencies
RUN pip install -r requirements.txt

#run the file
CMD ["streamlit","run","main.py"]


# EXPOSE 8501

# CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]