stages:
  data_ingestion:
    cmd: python backend/data_ingestion.py
    deps: 
      - data/loan_data.csv
      - backend/data_ingestion.py
  data_preprocess:
    cmd: python backend/data_preprocess.py
    deps:
      - data/loan_data.csv
      - backend/data_preprocess.py
    outs:
      - data/preprocessed.csv
  model_train:
    cmd: python backend/model_train.py
    deps:
      - data/preprocessed.csv
      - backend/model_train.py
