stages:
  backend/data_ingestion:
    cmd: python  data_ingestion.py
    deps: 
      - data/loan_data.csv
      - data_ingestion.py
  backend/data_preprocess:
    cmd: python  data_preprocess.py
    deps:
      - data/loan_data.csv
      - data_preprocess.py
    outs:
      - data/preprocessed.csv
  backend/model_train:
    cmd: python  model_train.py
    deps:
      - data/preprocessed.csv
      - model_train.py
  
  # backend/main:
  #   cmd: uvicorn backend.main:app 
  #   deps:
  #     - loan_predict.joblib
  #     - backend/main.py
  # frontend/main:
  #   cmd: streamlit run frontend/main.py
  #   deps:
  #     - frontend/main.py
  #     - backend/main.py
